### ISSUE TITLE
Crear libreria de constantes

### ISSUE THREAD

**Issue by valenia** [hunkstalker/Cinetics#26]
- [ ] - Es necesario para el path del php mailer

- [ ] - Valorar si es necesario para otros documentos

branch: constantes

**Comment by hunkstalker** [comment]
Working on!

**Comment by hunkstalker** [comment]
Se han creado constantes para las credenciales de conexión a bbdd, la configuración de phpmailer y el path del proyecto que se requiere por ahora para mandarlo por el correo de verificación.

**Comment by hunkstalker** [comment]
He hecho que los paths al proyecto se generen solos, ya no hay que cambiar nada a mano en cada proyecto local.
