### ISSUE TITLE
Caducidad mail contraseña

### ISSUE THREAD

**Issue by hunkstalker** [hunkstalker/Cinetics#80]
Lo tenemos puesto a 60 min, habría que rebajarlo al menos a 30 min.

**Comment by valenia** [comment]
- De este bug se deriva una mejora: poder informar al usuario que su email no está registrado y que por tanto no puede recuperar ninguna contraseña. Estaría bien redirigir-lo a una página donde tenga para elegir ir a la página de registro o la página de login.
